### ISSUE TITLE
Final To-Do List

### ISSUE THREAD

**Issue by joaops-sousa** [MrChase95/Sistema_Judocas#25]
###  Relacionadas ao código

- [x] Buscar Alunos/Profesores/Dojos por nome 

- [ ] Mostrar a carteira de um aluno ou professor vencida ( Adicionar Data no Registro e Conferir com o dia de hoje) 

- [x] Mostrar o registro de uma pessoa que tem dois perfis, Aluno e Professor  (Já está feito, apenas um lembrete para mostrar no código

- [x] Criar pagina de formularios auto-gerados para criação de Aluno, Professor, Dojo, Torneio

###  Finalizações

- [ ] Link das mudanças com o Front-End
